kodi: fix build for honister
Honister updated to libfmt 8.0. We need this to avoid:

StringUtils.h:98:32: error: no matching function for call to 'format(const wstring&, const wchar_t*&)'

Signed-off-by: MarkusVolk <f_l_k@t-online.de>