kodi_18: simplify mips overrides, fix CMake linking error
This happens with kodi 18.9 on vuduo2 using bfd or gold:

CMakeError.log
 ...
 [2/2] Linking C executable cmTC_1ac7c
 FAILED: cmTC_1ac7c
 ...
 ld.gold: error: cannot find -lpthreads
 ...
 error: undefined reference to 'pthread_create'
 collect2: error: ld returned 1 exit status
 ninja: build stopped: subcommand failed.

As seen in OpenPLi as of commit-id dc55339

Signed-off-by: Andrea Adami <andrea.adami@gmail.com>